name: Build JetBrains Plugin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive build outputs
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifacts
          path: build/libs/*.jar
